# Generated by Django 5.1.4 on 2025-03-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0004_illustration_bidding_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illustration',
            name='is_bidding_enabled',
        ),
        migrations.AddField(
            model_name='illustration',
            name='selling_type',
            field=models.CharField(choices=[('sell', 'Fixed Price'), ('bid', 'Live Bidding')], default='sell', max_length=10),
        ),
    ]
