# Generated by Django 5.1.4 on 2025-03-07 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0005_remove_illustration_is_bidding_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='illustration',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='illustration',
            name='is_bidding_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='illustration',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_illustrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
