# Generated by Django 5.1.4 on 2025-01-27 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_customuser_user_type_alter_customuser_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='illustrations/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('illustrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authenticate_illustrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
