# Generated by Django 5.1.4 on 2025-01-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_illustration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Illustration',
        ),
    ]
